kind: Deployment
apiVersion: apps/v1
metadata:
  name: habit-backend-dev
spec:
  replicas: 1
  selector:
      matchLabels:
          app: habit
          role: backend
          env: dev
  template:
    metadata:
      name: backend
      labels:
        app: habit
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: gcr.io/b21-cap0076/habit:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080