kind: Deployment
apiVersion: apps/v1
metadata:
  name: habit-backend-production
spec:
  replicas: 4
  selector:
      matchLabels:
          app: habit
          role: backend
          env: production
  template:
    metadata:
      name: backend
      labels:
        app: habit
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/b21-cap0076/habit:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /docs
            port: 8080
        command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8080"]
        ports:
        - name: backend
          containerPort: 8080