kind: Service
apiVersion: v1
metadata:
  name: habit-backend
spec:
  type: LoadBalancer
  loadBalancerIP: "34.126.96.253"
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: habit